version: "3.4"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - seo-db:/var/lib/postgresql/data/pgdata
  server:
    build: server
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  client:
    build: client
    command: nginx -g "daemon off;"
    ports:
      - 8080:80
    depends_on:
      - server
volumes:
  seo-db:
